# db configuration
spring:
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

#security configuration
security:
  oauth2:
    resource:
      id: oauth2_application


#access token expiration in seconds
access_token:
  validity_period: 3600

#refresh token expiration in seconds
refresh_token:
  validity_period: 10000